---
- name: "Basebox builder"
  hosts: builder
  sudo: no

  vars_prompt:
    - name: "template"
      prompt: "Choose your template"
      private: no

    - name: "box_name"
      prompt: "Name your basebox"
      private: no

    - name: "working_dir"
      prompt: "Choose your working directory"
      private: no
      default: "builder"

  tasks:
    - name: "Check if Vagrant is present"
      action: shell which vagrant

    - name: "Install Veewee from gems"
      action: gem name=veewee state=latest

    - name: "Install Veewee-templates-updater from gems"
      action: gem name=veewee-templates-updater state=latest

    - name: "Update Veewee templates"
      action: shell $(ruby -rubygems -e 'puts Gem.user_dir')/bin/veewee-templates-update

    - name: "Verify working directory"
      file: path={{working_dir}} state=directory mode=0755

    - name: "Define a new basebox"
      action: shell $(ruby -rubygems -e 'puts Gem.user_dir')/bin/veewee vbox define '{{box_name}}' '{{template}}' -f chdir={{working_dir}}

    - name: "Build a new basebox"
      action: shell $(ruby -rubygems -e 'puts Gem.user_dir')/bin/veewee vbox build '{{box_name}}' -f -a -n chdir={{working_dir}}

    - name: "Export the new basebox"
      action: shell $(ruby -rubygems -e 'puts Gem.user_dir')/bin/veewee vbox export '{{box_name}}' chdir={{working_dir}}
